import pytest
from .harness import Persona,PlaytestClient

@pytest.mark.playtest
@pytest.mark.asyncio
async def test_npc_schedule_moves_world_and_container_transfer_is_atomic() -> None:
    client=PlaytestClient(Persona(name="Owner",principal_id="owner"))
    try:
        await client.command("CreateCampaign",payload={"campaign_id":"cmp_living","seed":15});await client.command("CreateWorld",campaign_id="cmp_living",payload={"world_id":"world_living","locations":[{"id":"home","name":"Home","connections":["market"]},{"id":"market","name":"Market","connections":["home"]}]});await client.command("CreateActor",campaign_id="cmp_living",payload={"actor_id":"npc_living","name":"Merchant","controller":{"controller_type":"simple_npc","behavior_profile_ref":"passive"}});await client.command("PlaceActorInWorld",campaign_id="cmp_living",actor_id="npc_living",payload={"world_id":"world_living","location_id":"home"});await client.command("ConfigureWorldEnvironment",campaign_id="cmp_living",payload={"environment_id":"env_living","day_length":60});await client.command("ConfigureNpcPersonality",campaign_id="cmp_living",actor_id="npc_living",payload={"personality":{"disposition":"friendly","goals":["trade"]}});await client.command("ConfigureNpcSchedule",campaign_id="cmp_living",actor_id="npc_living",payload={"schedule":[{"step_id":"market_shift","minute_of_day":5,"world_id":"world_living","location_id":"market","activity":"trade"}]});await client.command("AdvanceSimulationTime",campaign_id="cmp_living",payload={"target_time":5});world=(await client.get("/api/v1/worlds/world_living"))["data"];assert world["actor_locations"]["npc_living"]=="market"
        await client.command("CreateActor",campaign_id="cmp_living",payload={"actor_id":"hero_living","name":"Hero","controller":{"controller_type":"human"}});await client.command("CreateContainer",campaign_id="cmp_living",payload={"container_id":"chest_living","name":"Chest","items":["testing:item/key"]});await client.command("TakeItemFromContainer",campaign_id="cmp_living",actor_id="hero_living",payload={"container_id":"chest_living","item_id":"testing:item/key"});actor=(await client.get("/api/v1/actors/hero_living"))["data"];assert "testing:item/key" in actor["inventory"];await client.command("StoreItemInContainer",campaign_id="cmp_living",actor_id="hero_living",payload={"container_id":"chest_living","item_id":"testing:item/key"});container=(await client.get("/api/v1/containers/chest_living"))["data"];assert "testing:item/key" in container["items"]
    finally:await client.close()
