import pytest

from .harness import Persona, PlaytestClient


async def _publish_pack(client: PlaytestClient, workspace_id: str, version: str, enemy_hp: int) -> None:
    await client.command("CreateAuthoringWorkspace", payload={"workspace_id": workspace_id, "namespace": "p8"})
    await client.command("UpsertDraftDefinition", payload={"workspace_id": workspace_id, "draft_id": "npc", "definition_type": "npc_template", "key": "p8:npc/raider", "source": {"license_id": "CC0-1.0"}, "data": {"name": "P8 Raider", "max_hp": enemy_hp, "attack_bonus": -5, "defense": 5, "behavior_profile": "aggressive_melee"}})
    await client.command("UpsertDraftDefinition", payload={"workspace_id": workspace_id, "draft_id": "encounter", "definition_type": "encounter_template", "key": "p8:encounter/camp", "source": {"license_id": "CC0-1.0"}, "data": {"enemy_ref": "p8:npc/raider", "player_side": "heroes", "enemy_side": "enemies", "player_position": 0, "enemy_position": 2}})
    validation = await client.command("ValidateAuthoringWorkspace", payload={"workspace_id": workspace_id}); assert validation["result"]["quality_report"]["valid"] is True
    await client.command("PublishAuthoringWorkspace", payload={"workspace_id": workspace_id, "version": version})


@pytest.mark.playtest
@pytest.mark.asyncio
async def test_p8_creator_to_release_recovery_journey() -> None:
    dm = PlaytestClient(Persona(name="DM", principal_id="p8-owner", role="owner")); player = None
    try:
        discovery = await dm.get("/api/v1/discovery"); assert discovery["data"]["creator"]["content_is_data_only"] is True
        await _publish_pack(dm, "p8_ws_v1", "1.0.0", 4)
        await dm.command("CreateCampaignDraft", payload={"draft_id":"p8_draft","campaign_id":"cmp_p8","name":"P8 Testing Grounds","seed":808,"template_id":"fast_timed_turns"})
        assert (await dm.command("ValidateCampaignDraft", payload={"draft_id":"p8_draft"}))["result"]["valid"] is True
        await dm.command("FinalizeCampaignDraft", payload={"draft_id":"p8_draft"}); await dm.command("BindCampaignContent", campaign_id="cmp_p8", payload={"pack_id":"p8","version":"1.0.0"})
        await dm.command("CreateGameSession", campaign_id="cmp_p8", payload={"session_id":"p8_session"}); invite = await dm.command("CreateSessionInvitation", campaign_id="cmp_p8", payload={"session_id":"p8_session","principal_id":"p8-player"})
        player = PlaytestClient(Persona(name="Player", principal_id="p8-player", role="player"), app=dm.app); await player.command("AcceptSessionInvitation", campaign_id="cmp_p8", payload={"session_id":"p8_session","invitation_id":invite["result"]["invitation_id"]})
        await player.command("StartCharacterCreation", campaign_id="cmp_p8", payload={"creation_id":"p8_cc"}); await player.command("SelectCharacterName", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","name":"Mira"}); await player.command("SelectCharacterClass", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","class_id":"mage"}); await player.command("SelectCharacterSubclass", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","subclass_id":"sage"}); await player.command("SelectCharacterSpecies", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","species":"elf"}); await player.command("SelectCharacterBackground", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","background":"scholar"}); await player.command("SelectCharacterAbilities", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","ability_scores":{"intelligence":15,"dexterity":14,"wisdom":13,"constitution":12,"charisma":10,"strength":8}}); await player.command("SelectCharacterProficiencies", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","proficiencies":["arcana","history"]}); await player.command("SelectCharacterEquipmentSet", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","equipment_set":"scholar"}); await player.command("SelectCharacterPreparedAbilities", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","prepared_abilities":["arcane_bolt","ward"]}); await player.command("FinalizeCharacterCreation", campaign_id="cmp_p8", payload={"creation_id":"p8_cc","actor_id":"p8_hero"})
        await dm.command("GrantActorControl", campaign_id="cmp_p8", payload={"session_id":"p8_session","actor_id":"p8_hero","principal_id":"p8-player"}); await dm.command("SetSessionReady", campaign_id="cmp_p8", payload={"session_id":"p8_session","ready":True}); await player.command("SetSessionReady", campaign_id="cmp_p8", payload={"session_id":"p8_session","ready":True}); await dm.command("OpenGameSession", campaign_id="cmp_p8", payload={"session_id":"p8_session"}); await dm.command("CreateParty", campaign_id="cmp_p8", payload={"party_id":"p8_party","name":"Heroes","member_actor_ids":["p8_hero"],"leader_actor_id":"p8_hero"})
        await dm.command("CreateWorld", campaign_id="cmp_p8", payload={"world_id":"p8_world","locations":[{"id":"town","name":"Town","connections":["market","road"]},{"id":"market","name":"Market","connections":["town"]},{"id":"road","name":"Road","connections":["town","camp"]},{"id":"camp","name":"Camp","connections":["road"]}]}); await dm.command("PlaceActorInWorld", campaign_id="cmp_p8", actor_id="p8_hero", payload={"world_id":"p8_world","location_id":"town"})
        await dm.command("CreateActor", campaign_id="cmp_p8", payload={"actor_id":"p8_merchant","name":"Merchant","controller":{"controller_type":"utility_ai","controller_version":"2"}}); await dm.command("PlaceActorInWorld", campaign_id="cmp_p8", actor_id="p8_merchant", payload={"world_id":"p8_world","location_id":"town"}); await dm.command("ConfigureWorldEnvironment", campaign_id="cmp_p8", payload={"environment_id":"p8_env","day_length":60,"weather":"clear"}); await dm.command("ConfigureNpcPersonality", campaign_id="cmp_p8", actor_id="p8_merchant", payload={"personality":{"disposition":"friendly","goals":["trade"]}}); await dm.command("ConfigureNpcSchedule", campaign_id="cmp_p8", actor_id="p8_merchant", payload={"schedule":[{"step_id":"market","minute_of_day":5,"world_id":"p8_world","location_id":"market","activity":"support"}]}); await dm.command("ConfigureControllerGoal", campaign_id="cmp_p8", actor_id="p8_merchant", payload={"goal":{"goal_id":"serve_customers","description":"help customers","priority":80,"desired_tags":["support"]}}); await dm.command("RememberControllerFact", campaign_id="cmp_p8", actor_id="p8_merchant", payload={"memory_id":"hero_arrived","summary":"a hero arrived in town","tags":["support"],"importance":70})
        await dm.command("CreateVendor", campaign_id="cmp_p8", payload={"vendor_id":"p8_vendor","name":"Market Stall","stock":{"p8:item/rope":2},"prices":{"p8:item/rope":3},"currency":100}); await dm.command("CreateFaction", campaign_id="cmp_p8", payload={"faction_id":"p8_watch","name":"Town Watch"}); await dm.command("CreateContainer", campaign_id="cmp_p8", payload={"container_id":"p8_chest","name":"Supply Chest","items":["p8:item/ration"]}); await player.command("TakeItemFromContainer", campaign_id="cmp_p8", actor_id="p8_hero", payload={"container_id":"p8_chest","item_id":"p8:item/ration"}); await player.command("BuyFromVendor", campaign_id="cmp_p8", actor_id="p8_hero", payload={"vendor_id":"p8_vendor","item_id":"p8:item/rope"})
        await dm.command("CreateQuest", campaign_id="cmp_p8", payload={"quest_id":"p8_quest","title":"Clear the Camp","objective":"Defeat the raider"}); await player.command("AcceptQuest", campaign_id="cmp_p8", actor_id="p8_hero", payload={"quest_id":"p8_quest"}); await dm.command("ScheduleCampaignEvent", campaign_id="cmp_p8", payload={"delay":5,"kind":"weather_roll","event_payload":{"environment_id":"p8_env"}}); await dm.command("AdvanceSimulationTime", campaign_id="cmp_p8", payload={"delta":5}); assert (await player.get("/api/v1/worlds/p8_world"))["data"]["actor_locations"]["p8_merchant"] == "market"
        await player.command("TravelActor", campaign_id="cmp_p8", actor_id="p8_hero", payload={"world_id":"p8_world","destination_id":"road"}); await player.command("TravelActor", campaign_id="cmp_p8", actor_id="p8_hero", payload={"world_id":"p8_world","destination_id":"camp"})
        await dm.command("InstantiateEncounterTemplate", campaign_id="cmp_p8", payload={"pack_id":"p8","version":"1.0.0","encounter_key":"p8:encounter/camp","player_actor_id":"p8_hero","enemy_actor_id":"p8_raider","encounter_id":"p8_enc"})
        for turn in range(30):
            encounter = (await player.get("/api/v1/encounters/p8_enc"))["data"]
            if encounter["status"] == "completed": break
            actions = (await player.get("/api/v1/actors/p8_hero/available-actions"))["data"]; chosen = next((item for item in actions if item["action_id"] == "ability:arcane_bolt"), next((item for item in actions if item["action_id"] in {"power_attack","attack"}), actions[0])); payload={"encounter_id":"p8_enc","action_id":chosen["action_id"]};
            if chosen.get("target_id") is not None: payload["target_id"] = chosen["target_id"]
            await player.command("PerformAction", campaign_id="cmp_p8", actor_id="p8_hero", idempotency_key=f"p8-turn-{turn}", payload=payload)
        assert (await player.get("/api/v1/encounters/p8_enc"))["data"]["status"] == "completed"; await player.command("CompleteQuest", campaign_id="cmp_p8", actor_id="p8_hero", payload={"quest_id":"p8_quest","required_encounter_id":"p8_enc"}); await dm.command("ChangeFactionReputation", campaign_id="cmp_p8", payload={"faction_id":"p8_watch","actor_id":"p8_hero","delta":10}); await player.command("TakeRest", campaign_id="cmp_p8", actor_id="p8_hero", payload={"rest_type":"long"}); await dm.command("CreateCheckpoint", campaign_id="cmp_p8", payload={"checkpoint_id":"p8_checkpoint","name":"Camp Cleared"})
        await _publish_pack(dm, "p8_ws_v2", "1.1.0", 6); await dm.command("ProposeContentRevision", campaign_id="cmp_p8", payload={"proposal_id":"p8_revision","to_version":"1.1.0"}); dry = await dm.command("DryRunContentRevision", campaign_id="cmp_p8", payload={"proposal_id":"p8_revision"}); assert dry["result"]["sandbox_report"]["isolated"] is True; await dm.command("ActivateContentRevision", campaign_id="cmp_p8", payload={"proposal_id":"p8_revision"}); assert (await dm.get("/api/v1/campaigns/cmp_p8/content-binding"))["data"]["version"] == "1.1.0"
        await dm.command("CloseGameSession", campaign_id="cmp_p8", payload={"session_id":"p8_session"}); recap = (await dm.get("/api/v1/sessions/p8_session/recap"))["data"]; assert recap["event_count"] > 0; journal=(await player.get("/api/v1/actors/p8_hero/journal"))["data"]; assert journal["entries"]
        replay = await dm.get("/api/v1/campaigns/cmp_p8/replay-hash"); assert replay["matches_live"] is True
        package = (await dm.get("/api/v1/campaigns/cmp_p8/export-package"))["data"]; validation = await dm.http.post("/api/v1/imports/campaign/validate", json=package, headers=dm.headers); validation.raise_for_status(); assert validation.json()["data"]["valid"] is True
        recovery = await dm.http.post("/api/v1/admin/recovery-probe/cmp_p8", headers={"x-principal-id":"admin","x-principal-roles":"admin"}); recovery.raise_for_status(); assert recovery.json()["data"]["success"] is True
        sync = await player.get("/api/v1/campaigns/cmp_p8/sync"); assert sync["data"]["mode"] == "snapshot"
        audit = await dm.http.get("/api/v1/admin/audit?campaign_id=cmp_p8", headers={"x-principal-id":"admin","x-principal-roles":"admin"}); audit.raise_for_status(); assert audit.json()["data"]
    finally:
        if player is not None: await player.close()
        await dm.close()
